workflows:
  ios-preview:
    name: iOS App Preview

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS Simulator App
        script: |
          flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/*.app