workflows:
  android-preview:
    name: Android Preview
    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk