name: aynsouq
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# SPLASH CONFIG
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true

# APP ICON CONFIG
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png